name: Build Documentation
description: 'Build Documentation.'

runs:
  using: composite
  steps:
    - name: Build Documentation
      shell: bash
      working-directory: packages/sdk/server-ai
      run: make docs
