# -*- coding: utf-8 -*-
# type: ignore
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

import os
import sys
from importlib.metadata import version as _pkg_version

# Add the openai provider package source to the path
sys.path.insert(0, os.path.abspath('../src'))

import ldai_openai  # noqa: F401

# -- Project information -----------------------------------------------------

project = u'launchdarkly-server-sdk-ai-openai'
copyright = u'2026, LaunchDarkly'
author = u'LaunchDarkly'

# The short X.Y version.
version = _pkg_version('launchdarkly-server-sdk-ai-openai')
# The full version, including alpha/beta/rc tags.
release = version


# -- General configuration ---------------------------------------------------

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['build']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# RTD sets html_theme = 'sphinx_rtd_theme' itself

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory.
html_static_path = ['_static']


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'launchdarkly-server-sdk-ai-openai-doc'


# -- Extension configuration -------------------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'ldai': ('https://launchdarkly-python-sdk-ai.readthedocs.io/en/latest/', None),
}

autodoc_default_options = {
    'undoc-members': False
}
