name: Shared CI Workflow
description: 'Build, lint, and test a package'
inputs:
  workspace_path:
    description: 'Path to the package to build/test.'
    required: true
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.11'

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Dependencies
      shell: bash
      run: uv sync --all-groups

    - name: Lint
      shell: bash
      run: make -C ${{ inputs.workspace_path }} lint

    - name: Test
      shell: bash
      run: make -C ${{ inputs.workspace_path }} test
